services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: cnap-app
    command: ["start"]
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-cnap}:${POSTGRES_PASSWORD:-cnap}@postgres:5432/${POSTGRES_DB:-cnap}?sslmode=disable
      ENV: ${APP_ENV:-development}
      LOG_LEVEL: ${APP_LOG_LEVEL:-info}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../docker-data/messages:/app/messages

  postgres:
    image: postgres:16-alpine
    container_name: cnap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cnap}
      POSTGRES_USER: ${POSTGRES_USER:-cnap}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cnap}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ../docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-cnap} -d ${POSTGRES_DB:-cnap}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
